### PR TITLE
Login and signup

### PR DESCRIPTION
**Pull request by ApurvaSawant11**
Hello,

This branch has the following components:
1. Navigation bar
2. Login Page
3. Signup Page

Note: Pages are linked. Click on `login` icon on the navigation to go to the login page.
Please review and suggest

### CODE REVIEW

**Review by Dev-AkshatGupta — APPROVED** [review]
LGTM and you UI looks dope :)

**Review by partha8 — APPROVED** [review]
LGTM

**Review by VLeads — APPROVED** [review]
Code is so clean.

**Review by VLeads — APPROVED** [review]
Looks good. UI is amazing 💯

**Comment by ApurvaSawant11** [comment]
> Looks good. UI is amazing 💯

Thank you so much :)

**Comment by ApurvaSawant11** [comment]
> LGTM and you UI looks dope :)

Thank you Akshat :)

**Pull request merged**
