### PR TITLE
Wishlist page

### PR DESCRIPTION
**Pull request by ApurvaSawant11**
Hello,

I have created a wishlist page. Please review and suggest.

### CODE REVIEW

**Review by partha8 — APPROVED** [review]
LGTM, I also learned a few things from your code. Great work and the UI looks good!

**Review by foolhardy21 — APPROVED** [review]
LGTM.

**Review by Dev-AkshatGupta — APPROVED** [review]
Looks cool to me

**Review by ParthParolekar — APPROVED** [review]
Everything looks good to me and the UI is so clean.

**Comment by ApurvaSawant11** [comment]
> LGTM, I also learned a few things from your code. Great work and the UI looks good!

Thanks, glad that you learned something new.

**Comment by ApurvaSawant11** [comment]
> Everything looks good to me and the UI is so clean.

Thank you, Parth!

**Pull request merged**
